# Generated by Django 6.0.3 on 2026-03-15 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rfq_text', models.TextField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('needs_review', 'Needs Review'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('rfq_source', models.CharField(choices=[('email', 'Email'), ('manual', 'Manual'), ('api', 'API')], default='api', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_description', models.TextField()),
                ('parsed_description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('match_method', models.CharField(blank=True, max_length=50)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catalogitem')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quoteworksheet')),
            ],
        ),
    ]
