# Generated by Django 6.0.3 on 2026-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='match_reason',
            field=models.TextField(blank=True),
        ),
    ]
