from django.contrib import admin
from .models import QuoteWorksheet, QuoteLineItem


class QuoteLineItemInline(admin.TabularInline):
    # Display quote line items directly within the QuoteWorksheet admin page
    # so users can review and edit items without navigating to another page.
    model = QuoteLineItem

    # Do not show extra empty forms by default when editing a worksheet.
    extra = 0

    # Fields shown for each line item in the worksheet admin view.
    fields = (
        "raw_description",
        "parsed_description",
        "quantity",
        "unit",
        "matched_catalog_item",
        "match_score",
        "match_method",
        "needs_review",
    )

    # Matching results are generated automatically by the system and
    # should not be manually edited in the admin interface.
    readonly_fields = ("match_score", "match_method")


@admin.register(QuoteWorksheet)
class QuoteWorksheetAdmin(admin.ModelAdmin):
    # Columns shown in the admin list view for quote worksheets.
    # These give admins a quick overview of incoming RFQs and their status.
    list_display = (
        "id",
        "customer_name",
        "customer_email",
        "status",
        "rfq_source",
        "created_at",
        "completed_at",
    )

    # Allow quick searching of worksheets by customer info or RFQ text.
    search_fields = ("customer_name", "customer_email", "rfq_text", "notes")

    # Filters in the admin sidebar for narrowing worksheets by workflow state.
    list_filter = ("status", "rfq_source", "created_at")

    # Show associated quote line items inline within the worksheet page.
    inlines = [QuoteLineItemInline]

    # Timestamp is system-generated and should not be editable.
    readonly_fields = ("created_at",)


@admin.register(QuoteLineItem)
class QuoteLineItemAdmin(admin.ModelAdmin):
    # Columns displayed when viewing line items directly in the admin.
    # Helps admins audit catalog matching results and item quantities.
    list_display = (
        "id",
        "worksheet",
        "raw_description",
        "quantity",
        "matched_catalog_item",
        "match_score",
        "match_method",
        "needs_review",
        "created_at",
    )

    # Enable searching by raw or parsed descriptions extracted from the RFQ.
    search_fields = ("raw_description", "parsed_description")

    # Sidebar filters to identify items needing manual review or inspect
    # how items were matched against the catalog.
    list_filter = ("needs_review", "match_method", "created_at")

    # Creation timestamp is automatically generated by the system.
    readonly_fields = ("created_at",)
